version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewProjectGitProject
  gitServerName: SanthoshK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.newprojectgit.integrations:New
  packages:
  - name: NewProjectGitProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1120
